project_id = "nfcwjredglbwjwuctfgy"

[functions.generate-script]
verify_jwt = false

[functions.generate-prompts]
verify_jwt = false

[functions.generate-ads-script]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
