// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfcwjredglbwjwuctfgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mY3dqcmVkZ2xid2p3dWN0Zmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDE0NjQsImV4cCI6MjA3MDQ3NzQ2NH0.GItEzhUkQ-CcArtAT0yeZcmwtmX7sGC3LEEMHwlqilU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});